# Generated by Django 2.2 on 2019-10-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pos_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='webapp.Choice', verbose_name='Вариант ответа'),
        ),
    ]
